### ISSUE TITLE
The menu does not pull up when I have my USB wifi card plugged in or when I have two physical wifi cards

### ISSUE THREAD

**Issue by t3zla** [firecat53/nmcli-dmenu#10]

**Comment by firecat53** [comment]
1. Are there any Python tracebacks at all?
2. Are you using dmenu or Rofi?
3. Does it work normally with just one adapter?
4. What's the output of ```nmcli -t -f name,type connections``` ?
5. What's the output of ```nmcli -t -f ssid,security,signal device wifi list```?

Are you able to download the source and step through the run() method using pdb so I can see exactly where it fails? It's going to be really difficult for me to troubleshoot not having an extra Wifi adapter!

Thanks,
Scott
Scott

**Comment by t3zla** [comment]
`nmcli -t -f name,type connections` 
says
`Error: Object 'connections' is unknown, try 'nmcli help'.`

and 
`nmcli -t -f ssid,security,signal device wifi list`
says

`2WIRE432:WPA1 WPA2:35`
`Cisco_7DE39603:WPA2:44`
`The Wire:WPA1 WPA2:19`

`2WIRE432:WPA1 WPA2:42`
`The Wire:WPA1 WPA2:35`
`Cisco_7DE39603:WPA2:44`
`NETGEAR80:WPA2:32`
`HP-Print-02-Officejet Pro 8600::62`
`Chromecast4447::35`

I usually run the program from j4-dmenu-desktop but when I run the command through terminal here is the output:

`Traceback (most recent call last):
  File "/usr/bin/nmcli_dmenu", line 317, in <module>
    run()
  File "/usr/bin/nmcli_dmenu", line 285, in run
    ssids = current_ssids()
  File "/usr/bin/nmcli_dmenu", line 86, in current_ssids
    res = sorted(res, key=lambda x: x[1], reverse=True)
  File "/usr/bin/nmcli_dmenu", line 86, in <lambda>
    res = sorted(res, key=lambda x: x[1], reverse=True)
IndexError: list index out of range
`

It has always worked with only 1 card, and i have tried it with multiple different external cards and whenever I have one plugged in along with my built in wifi card the command fails

**Comment by firecat53** [comment]
Ok, I see the issue. The ```nmcli device list``` command is returning the list of connections for each device and the script isn't setup to handle that.

Are you thinking that you should be able to pick which device to use for connecting to a network? It would be easier (for me at least) to add which device to use the config file. That's obviously less flexible than being able to select the device from the menu. I'll try to code something for you to test...gonna be interesting without having an extra device to test with :)

**Comment by firecat53** [comment]
I typo'd the first command I wanted you to run...should be (no 's' on connection):

    nmcli -t -f name,type connection

**Comment by firecat53** [comment]
Try the 'adapters' branch and see if that works for you. Thanks!

**Comment by t3zla** [comment]
That branch works perfectly. You cant connect to the same network with each card, but I'm not sure you can do that with network-manager anyways

**Comment by t3zla** [comment]
You also might want to make it so it only prompts you to choose an interface if there is more than one. Right now it prompts me even if I have my USB wifi card removed

**Comment by firecat53** [comment]
Yep...that was planned, but I didn't want any extra code confusing the issue! Glad it works for you.
Closed by 74dae047
