### ISSUE TITLE
What is the thing next to the name of the available connections in the new update? All I see are boxes. I assume I do not have a specific font installed

### ISSUE THREAD

**Issue by t3zla** [firecat53/nmcli-dmenu#17]

**Comment by firecat53** [comment]
Here's what it looks like on my machine. Can you post a picture of what you are seeing?
![2016-02-11-201608_1366x768_scrot](https://cloud.githubusercontent.com/assets/568113/12998792/9fdb79ce-d0fc-11e5-814e-8a27ffc3c74e.png)

**Comment by firecat53** [comment]
Closing this...let me know if your question didn't get answered.

Scott
