### ISSUE TITLE
Rofi support...?

### ISSUE THREAD

**Issue by arkhan** [firecat53/nmcli-dmenu#18]
It's posible to make rofi variant...?
https://davedavenport.github.io/rofi/

**Comment by firecat53** [comment]
Already has Rofi support. See the installation section of the README. You basically just need to set the executable in the configuration file.

Scott

**Comment by firecat53** [comment]
I'm gonna close this...if you have any trouble getting Rofi to work, feel free to re-open and I'll see what I can do.

Scott
