### ISSUE TITLE
Connecting to Network with Hidden SSID

### ISSUE THREAD

**Issue by monkeynaleo** [firecat53/nmcli-dmenu#25]
How do I connect to a network with a hidden ssid?  Is there a way with this?

**Comment by firecat53** [comment]
I think you would add the connection using nmtui or the Network Connections GUI and set it to auto-connect. There's no direct way to view/add the hidden connection with nmcli-dmenu. I don't know if it would show up in the menu or not after you added it manually. Let me know!

**Comment by firecat53** [comment]
Closing...let me know if you figured out anything.
