### ISSUE TITLE
Feature Request: Rofi Support

### ISSUE THREAD

**Issue by halocaridina** [firecat53/nmcli-dmenu#8]
Hi Scott,

Hope this finds you well. I've been extremely happy using nmcli-dmenu over the last few month. A couple of weeks ago, I switched from dmenu to rofi:

https://davedavenport.github.io/rofi/

for its window switching ability (installed as rofi-git from AUR). Is there the possibility of extending nmcli-dmenu to support rofi?

Thanks in advance,

halocaridina

**Comment by firecat53** [comment]
I'm going to go ahead and push this master. Let me know if any other issues arise with the Rofi support.

**Comment by DaveDavenport** [comment]
hmm never check all the extra options for dmenu when claiming rofi as replacement. (I should)
For me it was mostly it parsed the input the same way and produced output. 

What exactly is wrong with the prompt support? I thought it was '-p' for dmenu and for rofi.
Are there options that cause serious problems because of collision? if so that should be fixed.

**Comment by firecat53** [comment]
I'm sorry, I'm having a tough time figuring out what your questions are! Are you bringing up a new issue related to rofi support? If so, can you please open a new github issue for each problem/bug that you are seeing. 

Thanks!
Scott

**Comment by DaveDavenport** [comment]
Aah sorry, wasn't clear (yeah humans do not multitask).  I am the Rofi developer and was wondering if there are things in Rofi that should be fixed to make it a better drop in replacement.

**Comment by firecat53** [comment]
Ah, I see :) The only differences I found were:

1. Rofi uses -lines instead of -l
2. Rofi doesn't have a -i flag (for case insensitive)
3. Rofi has the -dmenu option

Those were the only differences I had to account for, and it was pretty minimal code, so no big deal!

**Comment by DaveDavenport** [comment]
From what I see the only collision is (1)`-l` in Rofi tells it what line to select. 

2. Rofi is case insensitive by default and passing -i should be silently ignored.
3. This can be solved by the symlink (and fixed the issue linked above).

I need to see what to do about "-l" as that might break clerk if I change it.

Thanks for the feedback (and sorry for polluting your bug)

**Comment by CumpsD** [comment]
@halocaridina would you mind sharing your `config.ini` please? I'm having a hard time grasping how things fit together.

I have a working `rofi` which I launch with a shortcut, linked to: `rofi -modi ssh,run,drun,window -lines 12 -padding 18 -width 60 -location 0 -show drun -sidebar-mode -columns 3 -font "Noto Sans 8"`

I installed `networkmanager-dmenu-git` on Arch, which is basically this repo. So I now have `networkmanager_dmenu` as a new command.

I copied the example config.ini to `~/.config/networkmanager-dmenu/config.ini` but then I am wondering, do I put my entire rofi line like above as `dmenu_command` or just `rofi`?

**Comment by CumpsD** [comment]
I think I got it a bit, this is my `config.ini`:

```
[dmenu]
dmenu_command = rofi -sidebar-mode -font "Noto Sans 8"

modi = ssh,run,drun,window
l = 12
padding = 18
width = 60
location = 0
show = drun
columns = 3
rofi_highlight = True
pinentry = pinentry

# nb = normal background (name, #RGB, or #RRGGBB)
# nf = normal foreground
# sb = selected background
# sf = selected foreground
# b =  (just set to empty value and menu will appear at the bottom
# m = number of monitor to display on
# p = Custom Prompt for the networks menu
```

I am guessing using this does not play wel together with `rofi -modi`?

Perhaps @DaveDavenport knows a trick for that?

**Comment by halocaridina** [comment]
@CumpsD 

Thanks for the questions and a copy of my configuration file can be found at:

https://github.com/halocaridina/.dotfiles_thinkpad_X270_crucial/blob/master/networkmanager-dmenu/.config/networkmanager-dmenu/config.ini

Many of the options you are trying to can no longer be set in that manner either as flags or in .Xresources. Instead, they have to be set in a rofi config file like:

https://github.com/halocaridina/.dotfiles_thinkpad_X270_crucial/tree/master/rofi/.config/rofi

Hope this helps.

**Comment by CumpsD** [comment]
@halocaridina thanks. not sure what you mean about not being able to set those as flags? The command with all flags works perfectly :) or you mean in combination with this repo?

**Comment by halocaridina** [comment]
Apologies and should clarify that don't work when using rofi in full screen (or how I'm running it).  See first comment at:

https://github.com/halocaridina/.dotfiles_thinkpad_X270_crucial/blob/master/Xresources/.local/share/Xresources/rofi.config

**Comment by CumpsD** [comment]
@halocaridina thanks to your advice, I moved over to rasi themes :) https://github.com/CumpsD/dotfiles/commit/505ed204b2a24bdd8d1eeae35e18d2e3c2326cba

I'm not using it fullscreen, but I was hoping to have this integrate as some sort of modi

**Comment by CumpsD** [comment]
You can tell I am still setting this computer, since I am unable to take a screenshot of my rofi :)

This is how my rofi looks:

![image](https://user-images.githubusercontent.com/1201644/62066760-5c68ed00-b232-11e9-99b5-d147bfa88cf7.png)

Notice at the bottom 4 modes, I was trying to get this in as an extra `wifi` mode, but no idea if it's possible even
