### ISSUE TITLE
Program doesn't work without a config file anymore

### ISSUE THREAD

**Issue by Alcesmire** [firecat53/nmcli-dmenu#9]
The last update broke usage without a config file. Unindent once at https://github.com/firecat53/nmcli-dmenu/blob/8616eb3cb1cf80b886a5fd08c498b845b8db8b4b/nmcli_dmenu#L60 and everything should be fine. I would make a pull request, but I'm lazy and this is a trivial fix.

**Comment by firecat53** [comment]
Thanks!
